-keep class io.flutter.** { *; }
-keep class io.flutter.embedding.** { *; }
-keep class io.flutter.plugins.** { *; }
-keep class com.google.firebase.** { *; }
-dontwarn io.flutter.embedding.**
-dontwarn java.lang.instrument.**
-keep class com.google.android.gms.** { *; }
-keepattributes SourceFile,LineNumberTable,*Annotation*
